// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr0-HFs-XbqoBT0v2ZMl1Kx2BCVsCM5dQ',
    appId: '1:1019553855248:web:d9e10931354131fd3b9795',
    messagingSenderId: '1019553855248',
    projectId: 'login-firebase-8d4f5',
    authDomain: 'login-firebase-8d4f5.firebaseapp.com',
    storageBucket: 'login-firebase-8d4f5.appspot.com',
    measurementId: 'G-HVB4RB3J3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-xQBlZI5mhR6qPZuLv3js8Hd4RePWn0',
    appId: '1:1019553855248:android:b8750c317dc29b513b9795',
    messagingSenderId: '1019553855248',
    projectId: 'login-firebase-8d4f5',
    storageBucket: 'login-firebase-8d4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-G0DiAG5cP60phjNj5ZMPdzqR0TZ29Yk',
    appId: '1:1019553855248:ios:e6e522c98fa719eb3b9795',
    messagingSenderId: '1019553855248',
    projectId: 'login-firebase-8d4f5',
    storageBucket: 'login-firebase-8d4f5.appspot.com',
    iosClientId: '1019553855248-p7v8g188m04qn854dbthss9fae35auvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-G0DiAG5cP60phjNj5ZMPdzqR0TZ29Yk',
    appId: '1:1019553855248:ios:e6e522c98fa719eb3b9795',
    messagingSenderId: '1019553855248',
    projectId: 'login-firebase-8d4f5',
    storageBucket: 'login-firebase-8d4f5.appspot.com',
    iosClientId: '1019553855248-p7v8g188m04qn854dbthss9fae35auvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
